from core.llm import call_agent
from core.models import SessionState

SYSTEM_PROMPT = """You are a senior QA engineer and code reviewer.

Given a task description, project context, and code generated by other agents, review the code for:
- Bugs and logic errors
- Security issues (SQL injection, XSS, auth bypasses, etc.)
- Missing error handling
- Test coverage gaps

Output a structured review with:
1. ISSUES: list of specific bugs or problems found
2. SUGGESTIONS: improvements to consider
3. VERDICT: PASS or NEEDS_FIXES

Be concise and actionable."""


def run(task_description: str, session: SessionState) -> str:
    # Collect previously generated code from completed tasks
    generated_code = []
    for task in session.task_queue:
        if task.result and task.agent in ("backend", "frontend"):
            generated_code.append(f"=== {task.description} ===\n{task.result}")

    code_context = "\n\n".join(generated_code) if generated_code else "No code generated yet."
    context = (
        f"Project: {session.user_request}\n\n"
        f"Task to review: {task_description}\n\n"
        f"Generated code:\n{code_context}"
    )
    return call_agent(SYSTEM_PROMPT, context)
